version: "3.1"
services:

  mysql:
    image: mysql:8.0
    container_name: sf5-mysql
    working_dir: /application
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sf5
    ports:
      - "3307:3306"
  redis:
    image: redis:4.0.1
    ports:
      - 6379:6379
    volumes:
      - ./local-dev/conf/redis:/etc/redis

#  webserver:
#    image: nginx:alpine
#    container_name: sf5-webserver
#    working_dir: /application
#    volumes:
#      - .:/application
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "8000:80"
#
#  php-fpm:
#    build: docker/php-fpm
#    container_name: smartredparrot-php
#    working_dir: /application
#    volumes:
#      - .:/application
#
#  app_messenger:
#    container_name: sf5-messenger
#    depends_on:
#      - php-fpm
#      - mysql
#    restart: on-failure
#    working_dir: /application
#    build: ./docker/consumer/
#    volumes:
#      - .:/application
#      - ./docker/consumer/supervisord.conf:/etc/supervisord.conf
